### ISSUE TITLE
sync feature is broken for EvalAltResult in 0.19

### ISSUE THREAD

**Issue by sunng87** [jonathandturner/rhai#269]
handlebars relies on the `sync` feature to have `EvalAltResult` as `Send + Sync`. However, the feature doesn't  seem to work in 0.19.x:

```
error[E0277]: `(dyn StdError + 'static)` cannot be sent between threads safely
   --> src/error.rs:75:9
    |
75  |         RenderError::from_error("Error on converting data to Rhai dynamic.", e)
    |         ^^^^^^^^^^^^^^^^^^^^^^^ `(dyn StdError + 'static)` cannot be sent between threads safely
...
109 |     pub fn from_error<E>(error_kind: &str, cause: E) -> RenderError
    |            ---------- required by a bound in this
110 |     where
111 |         E: Error + Send + Sync + 'static,
    |                    ---- required by this bound in `RenderError::from_error`
    |
    = help: the trait `Send` is not implemented for `(dyn StdError + 'static)`
    = note: required because of the requirements on the impl of `Send` for `Unique<(dyn StdError + 'static)>`
    = note: required because it appears within the type `Box<(dyn StdError + 'static)>`
    = note: required because it appears within the type `EvalAltResult`
    = note: required because of the requirements on the impl of `Send` for `Unique<EvalAltResult>`
    = note: required because it appears within the type `Box<EvalAltResult>`
```

Also it seems `serde` feature declaration was missing from `Cargo.toml` although it's used in `lib.rs`

**Comment by schungx** [comment]
> Also it seems `serde` feature declaration was missing from `Cargo.toml` although it's used in `lib.rs`

I think it can be omitted if the feature name is the same as the dependency name.  The `serde` feature should work normally.

I'll fix the problem with `Send + Sync`.

**Comment by sunng87** [comment]
Thanks for quick response. I think it's brought in with `ErrorSystem(Box<Error>)`

**Comment by schungx** [comment]
Yes.  Good catch. Forgot about the trait bound.

Can you wait until a bit later when I released `0.19.4`?  I'll fix it there.

**Comment by schungx** [comment]
Or you can use `0.19.2` or `0.19.0` for the time being.

**Comment by sunng87** [comment]
Thank you! I'm not in hurry so I will be waiting for 0.19.4 to adopt.
